/* Copyright (c) 2022 Synology Inc. All rights reserved. */

function Readability(a,c,e){e=e||{};this._uri=a;this._doc=c;this._biggestFrame=false;this._articleDir=this._articleByline=null;this._debug=!!e.debug;this._maxElemsToParse=e.maxElemsToParse||this.DEFAULT_MAX_ELEMS_TO_PARSE;this._nbTopCandidates=e.nbTopCandidates||this.DEFAULT_N_TOP_CANDIDATES;this._maxPages=e.maxPages||this.DEFAULT_MAX_PAGES;this._flags=this.FLAG_STRIP_UNLIKELYS|this.FLAG_WEIGHT_CLASSES|this.FLAG_CLEAN_CONDITIONALLY;this._parsedPages={};this._pageETags={};this._curPageNum=1;var h;
if(this._debug){h=function(i){var g=i.nodeName+" ";if(i.nodeType==i.TEXT_NODE)return g+'("'+i.textContent+'")';var f=i.className&&"."+i.className.replace(/ /g,"."),k="";if(i.id)k="(#"+i.id+f+")";else if(f)k="("+f+")";return g+k};this.log=function(){if(typeof dump!=="undefined"){var i=Array.prototype.map.call(arguments,function(g){return g&&g.nodeName?h(g):g}).join(" ");dump("Reader: (Readability) "+i+"\n")}else if(typeof console!==undefined){i=["Reader: (Readability) "].concat(arguments);console.log.apply(console,
i)}}}else this.log=function(){}}
Readability.prototype={FLAG_STRIP_UNLIKELYS:1,FLAG_WEIGHT_CLASSES:2,FLAG_CLEAN_CONDITIONALLY:4,DEFAULT_MAX_ELEMS_TO_PARSE:0,DEFAULT_N_TOP_CANDIDATES:5,DEFAULT_MAX_PAGES:5,DEFAULT_TAGS_TO_SCORE:"section,h2,h3,h4,h5,h6,p,td,pre,img".toUpperCase().split(","),REGEXPS:{unlikelyCandidates:/banner|combx|comment|community|disqus|extra|foot|header|legends|menu|modal|related|remark|rss|shoutbox|sidebar|skyscraper|sponsor|ad-break|agegate|pagination|pager|popup/i,okMaybeItsACandidate:/and|article|body|column|main|shadow/i,positive:/article|body|content|entry|hentry|h-entry|main|page|pagination|post|text|blog|story/i,
negative:/hidden|^hid$| hid$| hid |^hid |banner|combx|comment|com-|contact|foot|footer|footnote|masthead|media|meta|modal|outbrain|promo|related|scroll|share|shoutbox|sidebar|skyscraper|sponsor|shopping|tags|tool|widget/i,extraneous:/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|utility/i,byline:/byline|author|dateline|writtenby|p-author/i,replaceFonts:/<(\/?)font[^>]*>/gi,normalize:/\s{2,}/g,videos:/\/\/(www\.)?(dailymotion|youtube|youtube-nocookie|player\.vimeo)\.com/i,
nextLink:/(next|weiter|continue|>([^\|]|$)|\u00bb([^\|]|$))/i,prevLink:/(prev|earl|old|new|<|\u00ab)/i,whitespace:/^\s*$/,hasContent:/\S$/},DIV_TO_P_ELEMS:["A","BLOCKQUOTE","DL","DIV","IMG","OL","P","PRE","TABLE","UL","SELECT"],ALTER_TO_DIV_EXCEPTIONS:["DIV","ARTICLE","SECTION","P"],_postProcessContent:function(a){this._fixRelativeUris(a)},_removeNodes:function(a,c){for(var e=a.length-1;e>=0;e--){var h=a[e],i=h.parentNode;if(i)if(!c||c.call(this,h,e,a))i.removeChild(h)}},_forEachNode:function(a,c){Array.prototype.forEach.call(a,
c,this)},_someNode:function(a,c){return Array.prototype.some.call(a,c,this)},_concatNodeLists:function(){var a=Array.prototype.slice,c=a.call(arguments).map(function(e){return a.call(e)});return Array.prototype.concat.apply([],c)},_getAllNodesWithTag:function(a,c){if(a.querySelectorAll)return a.querySelectorAll(c.join(","));return[].concat.apply([],c.map(function(e){e=a.getElementsByTagName(e);return Array.isArray(e)?e:Array.from(e)}))},_fixRelativeUris:function(a){function c(g){if(/^[a-zA-Z][a-zA-Z0-9\+\-\.]*:/.test(g))return g;
if(g.substr(0,2)=="//")return e+"://"+g.substr(2);if(g[0]=="/")return h+g;if(g.indexOf("./")===0)return i+g.slice(2);if(g[0]=="#")return g;return i+g}var e=this._uri.scheme,h=this._uri.prePath,i=this._uri.pathBase;this._forEachNode(a.getElementsByTagName("a"),function(g){var f=g.getAttribute("href");if(f)if(f.indexOf("javascript:")===0){f=this._doc.createTextNode(g.textContent);g.parentNode.replaceChild(f,g)}else g.setAttribute("href",c(f))});this._forEachNode(a.getElementsByTagName("img"),function(g){var f=
g.getAttribute("src");f&&g.setAttribute("src",c(f))})},_getArticleTitle:function(){var a=this._doc,c="",e="";try{c=e=a.title;if(typeof c!=="string")c=e=this._getInnerText(a.getElementsByTagName("title")[0])}catch(h){}if(c.match(/ [\|\-] /)){c=e.replace(/(.*)[\|\-] .*/gi,"$1");if(c.split(" ").length<3)c=e.replace(/[^\|\-]*[\|\-](.*)/gi,"$1")}else if(c.indexOf(": ")!==-1){if(!this._someNode(this._concatNodeLists(a.getElementsByTagName("h1"),a.getElementsByTagName("h2")),function(i){return i.textContent===
c})){c=e.substring(e.lastIndexOf(":")+1);if(c.split(" ").length<3)c=e.substring(e.indexOf(":")+1)}}else if(c.length>150||c.length<15){a=a.getElementsByTagName("h1");if(a.length===1)c=this._getInnerText(a[0])}c=c.trim();if(c.split(" ").length<=4)c=e;return c},_prepDocument:function(){var a=this._doc;this._removeNodes(a.getElementsByTagName("style"));a.body&&this._replaceBrs(a.body);this._forEachNode(a.getElementsByTagName("font"),function(c){this._setNodeTag(c,"SPAN")})},_nextElement:function(a){for(a=
a;a&&a.nodeType!=Node.ELEMENT_NODE&&this.REGEXPS.whitespace.test(a.textContent);)a=a.nextSibling;return a},_replaceBrs:function(a){this._forEachNode(this._getAllNodesWithTag(a,["br"]),function(c){for(var e=c.nextSibling,h=false;(e=this._nextElement(e))&&e.tagName=="BR";){h=true;var i=e.nextSibling;e.parentNode.removeChild(e);e=i}if(h){h=this._doc.createElement("p");c.parentNode.replaceChild(h,c);for(e=h.nextSibling;e;){if(e.tagName=="BR")if((c=this._nextElement(e))&&c.tagName=="BR")break;c=e.nextSibling;
h.appendChild(e);e=c}}})},_setNodeTag:function(a,c){this.log("_setNodeTag",a,c);if(a.__JSDOMParser__){a.localName=c.toLowerCase();a.tagName=c.toUpperCase();return a}for(c=a.ownerDocument.createElement(c);a.firstChild;)c.appendChild(a.firstChild);a.parentNode.replaceChild(c,a);if(a.readability)c.readability=a.readability;for(var e=0;e<a.attributes.length;e++)c.setAttribute(a.attributes[e].name,a.attributes[e].value);return c},_prepArticle:function(a){this._cleanStyles(a);this._cleanConditionally(a,
"form");this._clean(a,"object");this._clean(a,"embed");this._clean(a,"h1");this._clean(a,"footer");this._forEachNode(a.children,function(c){this._cleanMatchedNodes(c,/share/)});a.getElementsByTagName("h2").length===1&&this._clean(a,"h2");this._clean(a,"iframe");this._cleanHeaders(a);this._cleanConditionally(a,"table");this._cleanConditionally(a,"ul");this._cleanConditionally(a,"div");this._removeNodes(a.getElementsByTagName("p"),function(c){var e=c.getElementsByTagName("img").length,h=c.getElementsByTagName("embed").length,
i=c.getElementsByTagName("object").length,g=c.getElementsByTagName("iframe").length;return e+h+i+g===0&&!this._getInnerText(c,false)});this._forEachNode(this._getAllNodesWithTag(a,["br"]),function(c){var e=this._nextElement(c.nextSibling);e&&e.tagName=="P"&&c.parentNode.removeChild(c)})},_initializeNode:function(a){a.readability={contentScore:0};switch(a.tagName){case "DIV":a.readability.contentScore+=5;break;case "PRE":case "TD":case "BLOCKQUOTE":a.readability.contentScore+=3;break;case "ADDRESS":case "OL":case "UL":case "DL":case "DD":case "DT":case "LI":case "FORM":a.readability.contentScore-=
3;break;case "H1":case "H2":case "H3":case "H4":case "H5":case "H6":case "TH":a.readability.contentScore-=5;break}a.readability.contentScore+=this._getClassWeight(a)},_removeAndGetNext:function(a){var c=this._getNextNode(a,true);a.parentNode.removeChild(a);return c},_getNextNode:function(a,c){if(!c&&a.firstElementChild)return a.firstElementChild;if(a.nextElementSibling)return a.nextElementSibling;do a=a.parentNode;while(a&&!a.nextElementSibling);return a&&a.nextElementSibling},_getNextNodeNoElementProperties:function(a,
c){function e(h){do h=h.nextSibling;while(h&&h.nodeType!==h.ELEMENT_NODE);return h}if(!c&&a.children[0])return a.children[0];if(c=e(a))return c;do if(a=a.parentNode)c=e(a);while(a&&!c);return a&&c},_checkByline:function(a,c){if(this._articleByline)return false;if(a.getAttribute!==undefined)var e=a.getAttribute("rel");if((e==="author"||this.REGEXPS.byline.test(c))&&this._isValidByline(a.textContent)){this._articleByline=a.textContent.trim();return true}return false},_getNodeAncestors:function(a,c){c=
c||0;for(var e=0,h=[];a.parentNode;){h.push(a.parentNode);if(c&&++e===c)break;a=a.parentNode}return h},_grabArticle:function(a){this.log("**** grabArticle ****");var c=this._doc,e=a!==null?true:false;a=a?a:this._doc.body;if(!a){this.log("No body found in document. Abort.");return null}for(var h=a.innerHTML;;){for(var i=this._flagIsActive(this.FLAG_STRIP_UNLIKELYS),g=[],f=this._doc.documentElement;f;){var k=f.className+" "+f.id;if(this._checkByline(f,k))f=this._removeAndGetNext(f);else{if(i)if(this.REGEXPS.unlikelyCandidates.test(k)&&
!this.REGEXPS.okMaybeItsACandidate.test(k)&&f.tagName!=="BODY"&&f.tagName!=="A"){this.log("Removing unlikely candidate - "+k);f=this._removeAndGetNext(f);continue}this.DEFAULT_TAGS_TO_SCORE.indexOf(f.tagName)!==-1&&g.push(f);if(f.tagName==="DIV")if(this._hasSinglePInsideElement(f)){k=f.children[0];f.parentNode.replaceChild(k,f);f=k}else if(this._hasSynoNscImgInsideElement(f)){f=this._setNodeTag(f,"P");g.push(f)}else if(this._hasChildBlockElement(f))this._forEachNode(f.childNodes,function(r){if(r.nodeType===
Node.TEXT_NODE){var v=c.createElement("p");v.textContent=r.textContent;v.style.display="inline";v.className="readability-styled";f.replaceChild(v,r)}});else{f=this._setNodeTag(f,"P");g.push(f)}f=this._getNextNode(f)}}var s=[];this._forEachNode(g,function(r){if(!(!r.parentNode||typeof r.parentNode.tagName==="undefined")){var v=this._getInnerText(r),b=r.querySelector("img[syno_nsc_img_node_size_score]");if(!(!b&&v.length<25)){r=this._getNodeAncestors(r,3);if(r.length!==0){var d=0;d+=1;d+=v.split(",").length;
if(b)d+=parseFloat(b.getAttribute("syno_nsc_img_node_size_score"),10);d+=Math.min(Math.floor(v.length/100),3);this._forEachNode(r,function(j,l){if(j.tagName){if(typeof j.readability==="undefined"){this._initializeNode(j);s.push(j)}j.readability.contentScore+=d/(l===0?1:l===1?2:l*3)}})}}}});i=[];g=0;for(k=s.length;g<k;g+=1){var n=s[g],p=n.readability.contentScore*(1-this._getLinkDensity(n));n.readability.contentScore=p;console.log("Candidate:",n,"with score "+p);for(var o=0;o<this._nbTopCandidates;o++){var t=
i[o];if(!t||p>t.readability.contentScore){i.splice(o,0,n);i.length>this._nbTopCandidates&&i.pop();break}}}i=i[0]||null;k=false;if(i===null||i.tagName==="BODY"){i=c.createElement("DIV");k=true;for(g=a.childNodes;g.length;){this.log("Moving child out:",g[0]);i.appendChild(g[0])}a.appendChild(i);this._initializeNode(i)}else if(i){g=i.parentNode;n=i.readability.contentScore;for(p=n/3;g&&g.readability;){o=g.readability.contentScore;if(o<p)break;if(o>n){i=g;break}n=g.readability.contentScore;g=g.parentNode}}n=
c.createElement("DIV");if(e)n.id="readability-content";p=Math.max(10,i.readability.contentScore*0.2);g=i.parentNode;o=g.children;t=0;for(var x=o.length;t<x;t++){var q=o[t],w=false;this.log("Looking at sibling node:",q,q.readability?"with score "+q.readability.contentScore:"");this.log("Sibling has score",q.readability?q.readability.contentScore:"Unknown");if(q===i)w=true;else{var y=0;if(q.className===i.className&&i.className!=="")y+=i.readability.contentScore*0.2;if(q.readability&&q.readability.contentScore+
y>=p)w=true;else if(q.nodeName==="P"){y=this._getLinkDensity(q);var A=this._getInnerText(q),z=A.length;if(z>80&&y<0.25)w=true;else if(z<80&&z>0&&y===0&&A.search(/\.( |$)/)!==-1)w=true}}if(w){this.log("Appending node:",q);if(this.ALTER_TO_DIV_EXCEPTIONS.indexOf(q.nodeName)===-1){this.log("Altering sibling:",q,"to div.");q=this._setNodeTag(q,"DIV")}n.appendChild(q);t-=1;x-=1}}this._debug&&this.log("Article content pre-prep: "+n.innerHTML);this._prepArticle(n);this._debug&&this.log("Article content post-prep: "+
n.innerHTML);if(this._curPageNum===1)if(k){i.id="readability-page-1";i.className="page"}else{k=c.createElement("DIV");k.id="readability-page-1";k.className="page";for(p=n.childNodes;p.length;)k.appendChild(p[0]);n.appendChild(k)}this._debug&&this.log("Article content after paging: "+n.innerHTML);if(this._getInnerText(n,true).length<500){a.innerHTML=h;if(this._flagIsActive(this.FLAG_STRIP_UNLIKELYS))this._removeFlag(this.FLAG_STRIP_UNLIKELYS);else if(this._flagIsActive(this.FLAG_WEIGHT_CLASSES))this._removeFlag(this.FLAG_WEIGHT_CLASSES);
else if(this._flagIsActive(this.FLAG_CLEAN_CONDITIONALLY))this._removeFlag(this.FLAG_CLEAN_CONDITIONALLY);else return null}else{this._someNode([g,i].concat(this._getNodeAncestors(g)),function(r){if(!r.tagName)return false;if(r=r.getAttribute("dir")){this._articleDir=r;return true}return false});return n}}},_isValidByline:function(a){if(typeof a=="string"||a instanceof String){a=a.trim();return a.length>0&&a.length<100}return false},_getArticleMetadata:function(){var a={},c={},e=/^\s*((twitter)\s*:\s*)?(description|title)\s*$/gi,
h=/^\s*og\s*:\s*(description|title)\s*$/gi;this._forEachNode(this._doc.getElementsByTagName("meta"),function(i){var g=i.getAttribute("name"),f=i.getAttribute("property");if([g,f].indexOf("author")!==-1)a.byline=i.getAttribute("content");else{var k=null;if(e.test(g))k=g;else if(h.test(f))k=f;if(k)if(i=i.getAttribute("content")){k=k.toLowerCase().replace(/\s/g,"");c[k]=i.trim()}}});if("description"in c)a.excerpt=c.description;else if("og:description"in c)a.excerpt=c["og:description"];else if("twitter:description"in
c)a.excerpt=c["twitter:description"];if("og:title"in c)a.title=c["og:title"];else if("twitter:title"in c)a.title=c["twitter:title"];return a},_removeScripts:function(a){this._removeNodes(a.getElementsByTagName("script"),function(c){c.nodeValue="";c.removeAttribute("src");return true});this._removeNodes(a.getElementsByTagName("noscript"))},_hasSinglePInsideElement:function(a){if(a.children.length!=1||a.children[0].tagName!=="P")return false;return!this._someNode(a.childNodes,function(c){return c.nodeType===
Node.TEXT_NODE&&this.REGEXPS.hasContent.test(c.textContent)})},_hasSynoNscImgInsideElement:function(a){return!!a.querySelector("img[syno_nsc_img_node_size_score]")},_hasChildBlockElement:function(a){return this._someNode(a.childNodes,function(c){return this.DIV_TO_P_ELEMS.indexOf(c.tagName)!==-1||this._hasChildBlockElement(c)})},_getInnerText:function(a,c){c=typeof c==="undefined"?true:c;a=a.textContent.trim();if(c)return a.replace(this.REGEXPS.normalize," ");return a},_getCharCount:function(a,c){c=
c||",";return this._getInnerText(a).split(c).length-1},_cleanStyles:function(a){if(a=a||this._doc){var c=a.firstChild;for(typeof a.removeAttribute==="function"&&a.className!=="readability-styled"&&a.removeAttribute("style");c!==null;){if(c.nodeType===c.ELEMENT_NODE){c.className!=="readability-styled"&&c.removeAttribute("style");this._cleanStyles(c)}c=c.nextSibling}}},_getLinkDensity:function(a){var c=this._getInnerText(a).length;if(c===0)return 0;var e=0;this._forEachNode(a.getElementsByTagName("a"),
function(h){e+=this._getInnerText(h).length});return e/c},_findBaseUrl:function(){for(var a=this._uri,c=a.path.split("?")[0].split("/").reverse(),e=[],h="",i=0,g=c.length;i<g;i+=1){var f=c[i];if(f.indexOf(".")!==-1){h=f.split(".")[1];h.match(/[^a-zA-Z]/)||(f=f.split(".")[0])}if(f.indexOf(",00")!==-1)f=f.replace(",00","");if(f.match(/((_|-)?p[a-z]*|(_|-))[0-9]{1,2}$/i)&&(i===1||i===0))f=f.replace(/((_|-)?p[a-z]*|(_|-))[0-9]{1,2}$/i,"");h=false;if(i<2&&f.match(/^\d{1,2}$/))h=true;if(i===0&&f.toLowerCase()===
"index")h=true;if(i<2&&f.length<3&&!c[0].match(/[a-z]/i))h=true;h||e.push(f)}return a.scheme+"://"+a.host+e.reverse().join("/")},_findNextPageLink:function(a){var c=this._uri,e={};a=a.getElementsByTagName("a");for(var h=this._findBaseUrl(),i=0,g=a.length;i<g;i+=1){var f=a[i],k=a[i].href.replace(/#.*$/,"").replace(/\/$/,"");if(!(k===""||k===h||k===c.spec||k in this._parsedPages))if(c.host===k.split(/\/+/g)[1]){var s=this._getInnerText(f);if(!(s.match(this.REGEXPS.extraneous)||s.length>25))if(k.replace(h,
"").match(/\d/)){if(k in e)e[k].linkText+=" | "+s;else e[k]={score:0,linkText:s,href:k};var n=e[k];if(k.indexOf(h)!==0)n.score-=25;var p=s+" "+f.className+" "+f.id;if(p.match(this.REGEXPS.nextLink))n.score+=50;if(p.match(/pag(e|ing|inat)/i))n.score+=25;if(p.match(/(first|last)/i))n.linkText.match(this.REGEXPS.nextLink)||(n.score-=65);if(p.match(this.REGEXPS.negative)||p.match(this.REGEXPS.extraneous))n.score-=50;if(p.match(this.REGEXPS.prevLink))n.score-=200;f=f.parentNode;for(var o=p=false;f;){var t=
f.className+" "+f.id;if(!p&&t&&t.match(/pag(e|ing|inat)/i)){p=true;n.score+=25}if(!o&&t&&t.match(this.REGEXPS.negative))if(!t.match(this.REGEXPS.positive)){n.score-=25;o=true}f=f.parentNode}if(k.match(/p(a|g|ag)?(e|ing|ination)?(=|\/)[0-9]{1,2}/i)||k.match(/(page|paging)/i))n.score+=25;if(k.match(this.REGEXPS.extraneous))n.score-=15;if(k=parseInt(s,10))if(k===1)n.score-=10;else n.score+=Math.max(0,10-k)}}}c=null;for(var x in e)if(e.hasOwnProperty(x))if(e[x].score>=50&&(!c||c.score<e[x].score))c=e[x];
e=null;if(c){e=c.href.replace(/\/$/,"");this.log("NEXT PAGE IS "+e);this._parsedPages[e]=true}return e},_successfulRequest:function(a){return a.status>=200&&a.status<300||a.status===304||a.status===0&&a.responseText},_ajax:function(a,c){function e(){if(h.readyState===4)if(this._successfulRequest(h))c.success&&c.success(h);else c.error&&c.error(h)}var h=new XMLHttpRequest;if(typeof c==="undefined")c={};h.onreadystatechange=e;h.open("get",a,true);h.setRequestHeader("Accept","text/html");try{h.send(c.postBody)}catch(i){c.error&&
c.error()}return h},_appendNextPage:function(a){var c=this._doc;this._curPageNum+=1;var e=c.createElement("DIV");e.id="readability-page-"+this._curPageNum;e.className="page";e.innerHTML='<p class="page-separator" title="Page '+this._curPageNum+'">&sect;</p>';c.getElementById("readability-content").appendChild(e);if(this._curPageNum>this._maxPages)e.innerHTML+="<div style='text-align: center'><a href='"+a+"'>View Next Page</a></div>";else(function(h,i){this._ajax(h,{success:function(g){var f=g.getResponseHeader("ETag");
if(f){if(f in this._pageETags){this.log("Exact duplicate page found via ETag. Aborting.");e.style.display="none";return}this._pageETags[f]=1}f=c.createElement("DIV");g=g.responseText.replace(/\n/g,"\uffff").replace(/<script.*?>.*?<\/script>/gi,"");g=g.replace(/\n/g,"\uffff").replace(/<script.*?>.*?<\/script>/gi,"");g=g.replace(/\uffff/g,"\n").replace(/<(\/?)noscript/gi,"<$1div");g=g.replace(this.REGEXPS.replaceFonts,"<$1span>");f.innerHTML=g;this._replaceBrs(f);this._flags=7;g=this._findNextPageLink(f);
if(f=this._grabArticle(f)){var k=f.getElementsByTagName("P").length?f.getElementsByTagName("P")[0]:null;if(k&&k.innerHTML.length>100)for(var s=1;s<=this._curPageNum;s+=1){var n=c.getElementById("readability-page-"+s);if(n&&n.innerHTML.indexOf(k.innerHTML)!==-1){this.log("Duplicate of page "+s+" - skipping.");e.style.display="none";this._parsedPages[h]=true;return}}this._removeScripts(f);i.innerHTML+=f.innerHTML;setTimeout(function(){this._postProcessContent(i)}.bind(this),500);g&&this._appendNextPage(g)}else this.log("No content found in page to append. Aborting.")}})}).bind(this)(a,
e)},_getClassWeight:function(a){if(!this._flagIsActive(this.FLAG_WEIGHT_CLASSES))return 0;var c=0;if(typeof a.className==="string"&&a.className!==""){if(this.REGEXPS.negative.test(a.className))c-=25;if(this.REGEXPS.positive.test(a.className))c+=25}if(typeof a.id==="string"&&a.id!==""){if(this.REGEXPS.negative.test(a.id))c-=25;if(this.REGEXPS.positive.test(a.id))c+=25}return c},_clean:function(a,c){var e=["object","embed","iframe"].indexOf(c)!==-1;this._removeNodes(a.getElementsByTagName(c),function(h){if(e){if(this.REGEXPS.videos.test([].map.call(h.attributes,
function(i){return i.value}).join("|")))return false;if(this.REGEXPS.videos.test(h.innerHTML))return false}return true})},_hasAncestorTag:function(a,c,e){e=e||3;c=c.toUpperCase();for(var h=0;a.parentNode;){if(h>e)return false;if(a.parentNode.tagName===c)return true;a=a.parentNode;h++}return false},_cleanConditionally:function(a,c){if(this._flagIsActive(this.FLAG_CLEAN_CONDITIONALLY)){var e=c==="ul"||c==="ol";this._removeNodes(a.getElementsByTagName(c),function(h){var i=this._getClassWeight(h);this.log("Cleaning Conditionally",
h);if(i+0<0)return true;if(this._getCharCount(h,",")<10){for(var g=h.getElementsByTagName("p").length,f=h.getElementsByTagName("img").length,k=h.getElementsByTagName("li").length-100,s=h.getElementsByTagName("input").length,n=0,p=h.getElementsByTagName("embed"),o=0,t=p.length;o<t;o+=1)this.REGEXPS.videos.test(p[o].src)||(n+=1);p=this._getLinkDensity(h);o=this._getInnerText(h).length;return f>g&&!this._hasAncestorTag(h,"figure")||!e&&k>g||s>Math.floor(g/3)||!e&&o<25&&(f===0||f>2)||!e&&i<25&&p>0.2||
i>=25&&p>0.5||n===1&&o<75||n>1}return false})}},_cleanMatchedNodes:function(a,c){var e=this._getNextNode(a,true);for(a=this._getNextNode(a);a&&a!=e;)a=c.test(a.className+" "+a.id)?this._removeAndGetNext(a):this._getNextNode(a)},_cleanHeaders:function(a){for(var c=1;c<3;c+=1)this._removeNodes(a.getElementsByTagName("h"+c),function(e){return this._getClassWeight(e)<0})},_flagIsActive:function(a){return(this._flags&a)>0},_addFlag:function(a){this._flags|=a},_removeFlag:function(a){this._flags&=~a},isProbablyReaderable:function(a){var c=
this._getAllNodesWithTag(this._doc,["p","pre"]),e=this._getAllNodesWithTag(this._doc,["div > br"]);if(e.length){var h=new Set;[].forEach.call(e,function(g){h.add(g.parentNode)});c=[].concat.apply(Array.from(h),c)}var i=0;return this._someNode(c,function(g){if(a&&!a(g))return false;var f=g.className+" "+g.id;if(this.REGEXPS.unlikelyCandidates.test(f)&&!this.REGEXPS.okMaybeItsACandidate.test(f))return false;if(g.matches&&g.matches("li p"))return false;g=g.textContent.trim().length;if(g<140)return false;
i+=Math.sqrt(g-140);if(i>20)return true;return false})},parse:function(){if(this._maxElemsToParse>0){var a=this._doc.getElementsByTagName("*").length;if(a>this._maxElemsToParse)throw new Error("Aborting parsing document; "+a+" elements found");}if(typeof this._doc.documentElement.firstElementChild==="undefined")this._getNextNode=this._getNextNodeNoElementProperties;this._removeScripts(this._doc);this._prepDocument();a=this._getArticleMetadata();var c=a.title||this._getArticleTitle(),e=this._grabArticle();
if(!e)return null;this.log("Grabbed: "+e.innerHTML);this._postProcessContent(e);if(!a.excerpt){var h=e.getElementsByTagName("p");if(h.length>0)a.excerpt=h[0].textContent.trim()}h=e.textContent;return{uri:this._uri,title:c,byline:a.byline||this._articleByline,dir:this._articleDir,content:e.innerHTML,textContent:h,length:h.length,excerpt:a.excerpt}}};
(function(a){function c(b){return b.replace(/[&<>]/g,function(d){return f[d]})}function e(b){return b.replace(/[&<>'"]/g,function(d){return f[d]})}function h(b){return b.replace(/&(quot|amp|apos|lt|gt);/g,function(d,j){return g[j]}).replace(/&#(?:x([0-9a-z]{1,4})|([0-9]{1,4}));/gi,function(d,j,l){d=parseInt(j||l,j?16:10);return String.fromCharCode(d)})}function i(b){function d(m){for(var u=m.children.length,B=0;B<u;B++){var C=m.children[B];if(l||C.tagName===b)j.push(C);d(C)}}b=b.toUpperCase();var j=
[],l=b==="*";d(this);return j}var g={lt:"<",gt:">",amp:"&",quot:'"',apos:"'"},f={"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&apos;"},k={alignmentBaseline:"alignment-baseline",background:"background",backgroundAttachment:"background-attachment",backgroundClip:"background-clip",backgroundColor:"background-color",backgroundImage:"background-image",backgroundOrigin:"background-origin",backgroundPosition:"background-position",backgroundPositionX:"background-position-x",backgroundPositionY:"background-position-y",
backgroundRepeat:"background-repeat",backgroundRepeatX:"background-repeat-x",backgroundRepeatY:"background-repeat-y",backgroundSize:"background-size",baselineShift:"baseline-shift",border:"border",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomLeftRadius:"border-bottom-left-radius",borderBottomRightRadius:"border-bottom-right-radius",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",borderCollapse:"border-collapse",borderColor:"border-color",
borderImage:"border-image",borderImageOutset:"border-image-outset",borderImageRepeat:"border-image-repeat",borderImageSlice:"border-image-slice",borderImageSource:"border-image-source",borderImageWidth:"border-image-width",borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",borderRadius:"border-radius",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",
borderSpacing:"border-spacing",borderStyle:"border-style",borderTop:"border-top",borderTopColor:"border-top-color",borderTopLeftRadius:"border-top-left-radius",borderTopRightRadius:"border-top-right-radius",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderWidth:"border-width",bottom:"bottom",boxShadow:"box-shadow",boxSizing:"box-sizing",captionSide:"caption-side",clear:"clear",clip:"clip",clipPath:"clip-path",clipRule:"clip-rule",color:"color",colorInterpolation:"color-interpolation",
colorInterpolationFilters:"color-interpolation-filters",colorProfile:"color-profile",colorRendering:"color-rendering",content:"content",counterIncrement:"counter-increment",counterReset:"counter-reset",cursor:"cursor",direction:"direction",display:"display",dominantBaseline:"dominant-baseline",emptyCells:"empty-cells",enableBackground:"enable-background",fill:"fill",fillOpacity:"fill-opacity",fillRule:"fill-rule",filter:"filter",cssFloat:"float",floodColor:"flood-color",floodOpacity:"flood-opacity",
font:"font",fontFamily:"font-family",fontSize:"font-size",fontStretch:"font-stretch",fontStyle:"font-style",fontVariant:"font-variant",fontWeight:"font-weight",glyphOrientationHorizontal:"glyph-orientation-horizontal",glyphOrientationVertical:"glyph-orientation-vertical",height:"height",imageRendering:"image-rendering",kerning:"kerning",left:"left",letterSpacing:"letter-spacing",lightingColor:"lighting-color",lineHeight:"line-height",listStyle:"list-style",listStyleImage:"list-style-image",listStylePosition:"list-style-position",
listStyleType:"list-style-type",margin:"margin",marginBottom:"margin-bottom",marginLeft:"margin-left",marginRight:"margin-right",marginTop:"margin-top",marker:"marker",markerEnd:"marker-end",markerMid:"marker-mid",markerStart:"marker-start",mask:"mask",maxHeight:"max-height",maxWidth:"max-width",minHeight:"min-height",minWidth:"min-width",opacity:"opacity",orphans:"orphans",outline:"outline",outlineColor:"outline-color",outlineOffset:"outline-offset",outlineStyle:"outline-style",outlineWidth:"outline-width",
overflow:"overflow",overflowX:"overflow-x",overflowY:"overflow-y",padding:"padding",paddingBottom:"padding-bottom",paddingLeft:"padding-left",paddingRight:"padding-right",paddingTop:"padding-top",page:"page",pageBreakAfter:"page-break-after",pageBreakBefore:"page-break-before",pageBreakInside:"page-break-inside",pointerEvents:"pointer-events",position:"position",quotes:"quotes",resize:"resize",right:"right",shapeRendering:"shape-rendering",size:"size",speak:"speak",src:"src",stopColor:"stop-color",
stopOpacity:"stop-opacity",stroke:"stroke",strokeDasharray:"stroke-dasharray",strokeDashoffset:"stroke-dashoffset",strokeLinecap:"stroke-linecap",strokeLinejoin:"stroke-linejoin",strokeMiterlimit:"stroke-miterlimit",strokeOpacity:"stroke-opacity",strokeWidth:"stroke-width",tableLayout:"table-layout",textAlign:"text-align",textAnchor:"text-anchor",textDecoration:"text-decoration",textIndent:"text-indent",textLineThrough:"text-line-through",textLineThroughColor:"text-line-through-color",textLineThroughMode:"text-line-through-mode",
textLineThroughStyle:"text-line-through-style",textLineThroughWidth:"text-line-through-width",textOverflow:"text-overflow",textOverline:"text-overline",textOverlineColor:"text-overline-color",textOverlineMode:"text-overline-mode",textOverlineStyle:"text-overline-style",textOverlineWidth:"text-overline-width",textRendering:"text-rendering",textShadow:"text-shadow",textTransform:"text-transform",textUnderline:"text-underline",textUnderlineColor:"text-underline-color",textUnderlineMode:"text-underline-mode",
textUnderlineStyle:"text-underline-style",textUnderlineWidth:"text-underline-width",top:"top",unicodeBidi:"unicode-bidi",unicodeRange:"unicode-range",vectorEffect:"vector-effect",verticalAlign:"vertical-align",visibility:"visibility",whiteSpace:"white-space",widows:"widows",width:"width",wordBreak:"word-break",wordSpacing:"word-spacing",wordWrap:"word-wrap",writingMode:"writing-mode",zIndex:"z-index",zoom:"zoom"},s={area:true,base:true,br:true,col:true,command:true,embed:true,hr:true,img:true,input:true,
link:true,meta:true,param:true,source:true,wbr:true},n=[" ","\t","\n","\r"],p={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12},o=function(){};o.prototype={attributes:null,childNodes:null,localName:null,nodeName:null,parentNode:null,textContent:null,nextSibling:null,previousSibling:null,firstChild:function(){return this.childNodes[0]||
null},firstElementChild:function(){return this.children[0]||null},lastChild:function(){return this.childNodes[this.childNodes.length-1]||null},lastElementChild:function(){return this.children[this.children.length-1]||null},appendChild:function(b){b.parentNode&&b.parentNode.removeChild(b);var d=this.lastChild;if(d)d.nextSibling=b;b.previousSibling=d;if(b.nodeType===o.ELEMENT_NODE){b.previousElementSibling=this.children[this.children.length-1]||null;this.children.push(b);b.previousElementSibling&&(b.previousElementSibling.nextElementSibling=
b)}this.childNodes.push(b);b.parentNode=this},removeChild:function(b){var d=this.childNodes,j=d.indexOf(b);if(j===-1)throw"removeChild: node not found";else{b.parentNode=null;var l=b.previousSibling,m=b.nextSibling;if(l)l.nextSibling=m;if(m)m.previousSibling=l;if(b.nodeType===o.ELEMENT_NODE){l=b.previousElementSibling;m=b.nextElementSibling;if(l)l.nextElementSibling=m;if(m)m.previousElementSibling=l;this.children.splice(this.children.indexOf(b),1)}b.previousSibling=b.nextSibling=null;b.previousElementSibling=
b.nextElementSibling=null;return d.splice(j,1)[0]}},replaceChild:function(b,d){var j=this.childNodes,l=j.indexOf(d);if(l===-1)throw"replaceChild: node not found";else{b.parentNode&&b.parentNode.removeChild(b);j[l]=b;b.nextSibling=d.nextSibling;b.previousSibling=d.previousSibling;if(b.nextSibling)b.nextSibling.previousSibling=b;if(b.previousSibling)b.previousSibling.nextSibling=b;b.parentNode=this;if(b.nodeType===o.ELEMENT_NODE)if(d.nodeType===o.ELEMENT_NODE){b.previousElementSibling=d.previousElementSibling;
b.nextElementSibling=d.nextElementSibling;if(b.previousElementSibling)b.previousElementSibling.nextElementSibling=b;if(b.nextElementSibling)b.nextElementSibling.previousElementSibling=b;this.children[this.children.indexOf(d)]=b}else{b.previousElementSibling=function(){for(var m=l-1;m>=0;m--)if(j[m].nodeType===o.ELEMENT_NODE)return j[m];return null}();b.nextElementSibling=b.previousElementSibling?b.previousElementSibling.nextElementSibling:function(){for(var m=l+1;m<j.length;m++)if(j[m].nodeType===
o.ELEMENT_NODE)return j[m];return null}();if(b.previousElementSibling)b.previousElementSibling.nextElementSibling=b;if(b.nextElementSibling)b.nextElementSibling.previousElementSibling=b;b.nextElementSibling?this.children.splice(this.children.indexOf(b.nextElementSibling),0,b):this.children.push(b)}else if(d.nodeType===o.ELEMENT_NODE){if(d.previousElementSibling)d.previousElementSibling.nextElementSibling=d.nextElementSibling;if(d.nextElementSibling)d.nextElementSibling.previousElementSibling=d.previousElementSibling;
this.children.splice(this.children.indexOf(d),1)}d.parentNode=null;d.previousSibling=null;d.nextSibling=null;if(d.nodeType===o.ELEMENT_NODE){d.previousElementSibling=null;d.nextElementSibling=null}return d}},__JSDOMParser__:true};for(var t in p)o[t]=o.prototype[t]=p[t];var x=function(b,d){this.name=b;this._value=d};x.prototype={value:function(){return this._value},setValue:function(b){this._value=b;delete this._decodedValue},setDecodedValue:function(b){this._value=e(b);this._decodedValue=b},getDecodedValue:function(){if(typeof this._decodedValue===
"undefined")this._decodedValue=this._value&&h(this._value)||"";return this._decodedValue}};var q=function(){this.childNodes=[]};q.prototype={__proto__:o.prototype,nodeName:"#comment",nodeType:o.COMMENT_NODE};var w=function(){this.childNodes=[]};w.prototype={__proto__:o.prototype,nodeName:"#text",nodeType:o.TEXT_NODE,textContent:function(){if(typeof this._textContent==="undefined")this._textContent=h(this._innerHTML||"");return this._textContent},innerHTML:function(){if(typeof this._innerHTML==="undefined")this._innerHTML=
c(this._textContent||"");return this._innerHTML},innerHTML:function(b){this._innerHTML=b;delete this._textContent},textContent:function(b){this._textContent=b;delete this._innerHTML}};var y=function(){this.styleSheets=[];this.childNodes=[];this.children=[]};y.prototype={__proto__:o.prototype,nodeName:"#document",nodeType:o.DOCUMENT_NODE,title:"",getElementsByTagName:i,getElementById:function(b){function d(j){var l=j.children.length;if(j.id===b)return j;for(var m=0;m<l;m++){var u=d(j.children[m]);
if(u)return u}return null}return d(this)},createElement:function(b){return new A(b)},createTextNode:function(b){var d=new w;d.textContent=b;return d}};var A=function(b){this.attributes=[];this.childNodes=[];this.children=[];this.nextElementSibling=this.previousElementSibling=null;this.localName=b.toLowerCase();this.tagName=b.toUpperCase();this.style=new z(this)};A.prototype={__proto__:o.prototype,nodeType:o.ELEMENT_NODE,getElementsByTagName:i,className:function(){return this.getAttribute("class")||
""},className:function(b){this.setAttribute("class",b)},id:function(){return this.getAttribute("id")||""},id:function(b){this.setAttribute("id",b)},href:function(){return this.getAttribute("href")||""},href:function(b){this.setAttribute("href",b)},src:function(){return this.getAttribute("src")||""},src:function(b){this.setAttribute("src",b)},nodeName:function(){return this.tagName},innerHTML:function(){function b(j){var l=0;for(l=0;l<j.childNodes.length;l++){var m=j.childNodes[l];if(m.localName){d.push("<"+
m.localName);for(var u=0;u<m.attributes.length;u++){var B=m.attributes[u],C=B.value,D=C.indexOf('"')===-1?'"':"'";d.push(" "+B.name+"="+D+C+D)}if(m.localName in s&&!m.childNodes.length)d.push("/>");else{d.push(">");b(m);d.push("</"+m.localName+">")}}else d.push(m.innerHTML)}}var d=[];b(this);return d.join("")},innerHTML:function(b){b=(new v).parse(b);for(var d=this.childNodes.length;--d>=0;)this.childNodes[d].parentNode=null;this.childNodes=b.childNodes;this.children=b.children;for(d=this.childNodes.length;--d>=
0;)this.childNodes[d].parentNode=this},textContent:function(b){for(var d=this.childNodes.length;--d>=0;)this.childNodes[d].parentNode=null;d=new w;this.childNodes=[d];this.children=[];d.textContent=b;d.parentNode=this},textContent:function(){function b(j){j=j.childNodes;for(var l=0;l<j.length;l++){var m=j[l];m.nodeType===3?d.push(m.textContent):b(m)}}var d=[];b(this);return d.join("")},getAttribute:function(b){for(var d=this.attributes.length;--d>=0;){var j=this.attributes[d];if(j.name===b)return j.getDecodedValue()}},
setAttribute:function(b,d){for(var j=this.attributes.length;--j>=0;){var l=this.attributes[j];if(l.name===b){l.setDecodedValue(d);return}}this.attributes.push(new x(b,e(d)))},removeAttribute:function(b){for(var d=this.attributes.length;--d>=0;)if(this.attributes[d].name===b){this.attributes.splice(d,1);break}}};var z=function(b){this.node=b};z.prototype={getStyle:function(b){var d=this.node.getAttribute("style");if(d){d=d.split(";");for(var j=0;j<d.length;j++){var l=d[j].split(":");if(l[0].trim()===
b)return l[1].trim()}}},setStyle:function(b,d){var j=this.node.getAttribute("style")||"",l=0;do{var m=j.indexOf(";",l)+1,u=m-l-1;u=u>0?j.substr(l,u):j.substr(l);if(u.substr(0,u.indexOf(":")).trim()===b){j=j.substr(0,l).trim()+(m?" "+j.substr(m).trim():"");break}l=m}while(l);j+=" "+b+": "+d+";";this.node.setAttribute("style",j.trim())}};for(var r in k)(function(b){z.prototype.__defineGetter__(r,function(){return this.getStyle(b)});z.prototype.__defineSetter__(r,function(d){this.setStyle(b,d)})})(k[r]);
var v=function(){this.currentChar=0;this.strBuf=[];this.retPair=[];this.errorState=""};v.prototype={error:function(b){dump("JSDOMParser error: "+b+"\n");this.errorState+=b+"\n"},peekNext:function(){return this.html[this.currentChar]},nextChar:function(){return this.html[this.currentChar++]},readString:function(b){var d=this.html.indexOf(b,this.currentChar);if(d===-1){this.currentChar=this.html.length;b=null}else{b=this.html.substring(this.currentChar,d);this.currentChar=d+1}return b},readAttribute:function(b){var d=
"",j=this.html.indexOf("=",this.currentChar);if(j===-1)this.currentChar=this.html.length;else{d=this.html.substring(this.currentChar,j);this.currentChar=j+1}if(d){j=this.nextChar();if(j!=='"'&&j!=="'")this.error("Error reading attribute "+d+", expecting '\"'");else{j=this.readString(j);b.attributes.push(new x(d,j))}}},makeElementNode:function(b){var d=this.nextChar(),j=this.strBuf;for(j.length=0;n.indexOf(d)==-1&&d!==">"&&d!=="/";){if(d===undefined)return false;j.push(d);d=this.nextChar()}j=j.join("");
if(!j)return false;for(var l=new A(j);d!=="/"&&d!==">";){if(d===undefined)return false;for(;n.indexOf(this.html[this.currentChar++])!=-1;);this.currentChar--;d=this.nextChar();if(d!=="/"&&d!==">"){--this.currentChar;this.readAttribute(l)}}var m=false;if(d==="/"){m=true;d=this.nextChar();if(d!==">"){this.error("expected '>' to close "+j);return false}}b[0]=l;b[1]=m;return true},match:function(b){var d=b.length;if(this.html.substr(this.currentChar,d).toLowerCase()===b.toLowerCase()){this.currentChar+=
d;return true}return false},discardTo:function(b){b=this.html.indexOf(b,this.currentChar)+b.length;if(b===-1)this.currentChar=this.html.length;this.currentChar=b},readChildren:function(b){for(var d;d=this.readNode();)d.nodeType!==8&&b.appendChild(d)},readScript:function(b){for(;this.currentChar<this.html.length;){var d=this.nextChar(),j=this.peekNext();if(d==="<"){if(j==="!"||j==="?"){this.currentChar++;b.appendChild(this.discardNextComment());continue}if(j==="/"&&this.html.substr(this.currentChar,
8).toLowerCase()=="/script>"){this.currentChar--;return}}j=(d=b.lastChild&&b.lastChild.nodeType===o.TEXT_NODE)?b.lastChild:new w;var l=this.html.indexOf("<",this.currentChar);this.currentChar--;if(l===-1){j.innerHTML+=this.html.substring(this.currentChar,this.html.length);this.currentChar=this.html.length}else{j.innerHTML+=this.html.substring(this.currentChar,l);this.currentChar=l}d||b.appendChild(j)}},discardNextComment:function(){if(this.match("--"))this.discardTo("--\>");else for(var b=this.nextChar();b!==
">";){if(b===undefined)return null;if(b==='"'||b==="'")this.readString(b);b=this.nextChar()}return new q},readNode:function(){var b=this.nextChar();if(b===undefined)return null;if(b!=="<"){--this.currentChar;b=new w;var d=this.html.indexOf("<",this.currentChar);if(d===-1){b.innerHTML=this.html.substring(this.currentChar,this.html.length);this.currentChar=this.html.length}else{b.innerHTML=this.html.substring(this.currentChar,d);this.currentChar=d}return b}b=this.peekNext();if(b==="!"||b==="?"){this.currentChar++;
return this.discardNextComment()}if(b==="/"){--this.currentChar;return null}if(!this.makeElementNode(this.retPair))return null;b=this.retPair[0];d=b.localName;if(!this.retPair[1]){d=="script"?this.readScript(b):this.readChildren(b);var j="</"+d+">";if(!this.match(j)){this.error("expected '"+j+"' and got "+this.html.substr(this.currentChar,j.length));return null}}if(d==="title"&&!this.doc.title)this.doc.title=b.textContent.trim();else if(d==="head")this.doc.head=b;else if(d==="body")this.doc.body=
b;else if(d==="html")this.doc.documentElement=b;return b},parse:function(b){this.html=b;b=this.doc=new y;this.readChildren(b);if(b.documentElement)for(var d=b.childNodes.length;--d>=0;){var j=b.childNodes[d];j!==b.documentElement&&b.removeChild(j)}return b}};a.Node=o;a.Comment=q;a.Document=y;a.Element=A;a.Text=w;a.JSDOMParser=v})(this);
